name: Validate Min Terraform Version Compatibility

on:
  pull_request:
    branches:
    - main

permissions: {}

jobs:
  folders:
    name: Collect terraform directories
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      directories: ${{ steps.dirs.outputs.directories }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        show-progress: false
    - name: Get directories
      id: dirs
      uses: clowdhaus/terraform-composite-actions/directories@26118b78561fb44052ce9ab6c5ab850df70b9aa0 # v 1.13.0

  validate:
    name: Validate Terraform
    needs: folders
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        directory: ${{ fromJson(needs.folders.outputs.directories) }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        show-progress: false
    - name: Get minimum Terrafrom version
      id: tfversion
      uses: clowdhaus/terraform-min-max@04440fe3b2a1e64eb5ad115f8f7c57c4d6a54333 # v1.4.1
      with:
        directory: ${{ matrix.directory }}
    - name: Validate with Terraform ${{ steps.tfversion.outputs.minVersion }}
      uses: clowdhaus/terraform-composite-actions/pre-commit@26118b78561fb44052ce9ab6c5ab850df70b9aa0 # v 1.13.0
      with:
        terraform-version: ${{ steps.tfversion.outputs.minVersion }}
        args: 'terraform_validate --color=always --show-diff-on-failure --files ${{ matrix.directory }}/*'
        terraform-docs-version: v0.20.0
