name: Validate Min Terraform Version Compatibility

on:
  pull_request:
    branches:
    - main

permissions: {}

jobs:
  folders:
    name: Collect terraform directories
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        show-progress: false
    - name: Get directories
      id: dirs
      uses: clowdhaus/terraform-composite-actions/directories@8aef6513928e6e56c30662afb34a21bf4bf5d9f4 # v 1.11.1

  validate:
    name: Validate Terraform
    needs: folders
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        directory: ${{ fromJson(needs.folders.outputs.directories) }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        show-progress: false
    - name: Get minimum Terrafrom version
      id: tfversion
      uses: clowdhaus/terraform-min-max@04440fe3b2a1e64eb5ad115f8f7c57c4d6a54333 # v1.4.1
      with:
        directory: ${{ matrix.directory }}
    - name: Validate with Terraform ${{ steps.tfversion.outputs.minVersion }}
      uses: clowdhaus/terraform-composite-actions/pre-commit@8aef6513928e6e56c30662afb34a21bf4bf5d9f4 # v 1.11.1
      with:
        terraform-version: ${{ steps.tfversion.outputs.minVersion }}
        args: 'terraform_validate --color=always --show-diff-on-failure --files ${{ matrix.directory }}/*'
        terraform-docs-version: v0.20.0
